In [1]:
import torch
import numpy as np
print("set up successfully!")

set up successfully!


### What is a tensor?
Tensor is a type of data structure. We use tensors to encode inputs and outputs of a model, and its parameters.

### How to initialize a tensor?
- from data structure in python
- from numpy array
- from existed tensor (inherit datatype, shape and device)
- from a given shape, datatype, device and form of values

In [28]:
# 1. created directly from data 
# like tuple, list, numpy or the mixture, cannot be dictionary
data = [([1,2],(3,4)),[[5,6],(7,8)]]
x_data = torch.tensor(data) # a copy from list
print(x_data)

# they are independent
data[1][0][1] = 114514
print(x_data)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [26]:
# 2. created from numpy
np_array = np.array([[1,2],[3,4]])
x_np = torch.from_numpy(np_array) # sharing data between numpy and tensor
# x_np = torch.tensor(np_array) copy data from numpy to tensor
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [27]:
# 1. 创建一个 NumPy 数组
np_array = np.array([[1, 2], [3, 4]])
print(f"原始 NumPy 数组:\n{np_array}\n")

# 2. 使用 from_numpy() 创建 Tensor
tensor_from_numpy = torch.from_numpy(np_array)
print(f"用 from_numpy() 创建的 Tensor:\n{tensor_from_numpy}\n")

# 3. 使用 tensor() 创建 Tensor
tensor_copied = torch.tensor(np_array)
print(f"用 tensor() 创建的 Tensor:\n{tensor_copied}\n")

# --- 修改原始的 NumPy 数组 ---
print("="*30)
print("修改 NumPy 数组的第一个元素为 99")
np_array[0, 0] = 99
print("="*30)


# 4. 再次查看两个 Tensor 的值
print(f"修改后，原始 NumPy 数组:\n{np_array}\n")
print(f"修改后，from_numpy() 创建的 Tensor (它也变了！):\n{tensor_from_numpy}\n")
print(f"修改后，tensor() 创建的 Tensor (它没变):\n{tensor_copied}\n")

原始 NumPy 数组:
[[1 2]
 [3 4]]

用 from_numpy() 创建的 Tensor:
tensor([[1, 2],
        [3, 4]])

用 tensor() 创建的 Tensor:
tensor([[1, 2],
        [3, 4]])

修改 NumPy 数组的第一个元素为 99
修改后，原始 NumPy 数组:
[[99  2]
 [ 3  4]]

修改后，from_numpy() 创建的 Tensor (它也变了！):
tensor([[99,  2],
        [ 3,  4]])

修改后，tensor() 创建的 Tensor (它没变):
tensor([[1, 2],
        [3, 4]])



In [36]:
# 3. created from another tensor
x_ones = torch.ones_like(x_data) # retain or inherit properties from x_data (shape, datatype)
print(f"Ones Tensor: \n {x_ones} \n")
print(f"datatype of x_data: {x_data.dtype}")

x_rand = torch.rand_like(x_data, dtype=torch.float) # override the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]) 

datatype of x_data: torch.int64
Random Tensor: 
 tensor([[[0.3476, 0.4863],
         [0.2638, 0.3968]],

        [[0.3107, 0.0655],
         [0.1200, 0.3821]]]) 



In [25]:
# 4. created with random value, 0s or 1s
shape = (2,3,)
rand_tensor = torch.rand(shape)
zeros_tensor = torch.zeros((1,2,4,3)) # defalute dtype: float32
ones_tensor = torch.ones(4,5,6) # dtype: float32

print(f"random tensor: \n {rand_tensor} \n")
print(f"zeros tensor: \n {zeros_tensor} \n")
print(f"ones tensor: \n {ones_tensor} \n")

random tensor: 
 tensor([[0.5354, 0.4020, 0.4009],
        [0.6146, 0.9815, 0.3671]]) 

zeros tensor: 
 tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]) 

ones tensor: 
 tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1

### Attributes of a tensor
- shape 
- data type
- device

In [37]:
tensor = torch.ones((2,3,4),dtype=torch.int64)

print(f"tensor: {tensor}")
print(f"shape of tensor is: {tensor.shape}")
print(f"datatype of tensor is: {tensor.dtype}")
print(f"device tensor is stored on: {tensor.device}")

tensor: tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])
shape of tensor is: torch.Size([2, 3, 4])
datatype of tensor is: torch.int64
device tensor is stored on: cpu


### Operations on Tensors

In [42]:
# 1. move tensor to current accelerator if available
cpu_tensor = torch.rand((3,2,4))
print(f"Currently cpu_tensor is stored on: {cpu_tensor.device}")

if torch.accelerator.is_available():
    current_accelerator = torch.accelerator.current_accelerator()
    print(f"Current accelerator is: {current_accelerator}")
    print(f"We copy this tensor from cpu to {current_accelerator}")
    acc_tensor = cpu_tensor.to(torch.accelerator.current_accelerator())
    print(f"Now the copy of tensor: \n{acc_tensor}\n is stored on {current_accelerator}")

Currently cpu_tensor is stored on: cpu
Current accelerator is: cuda
We copy this tensor from cpu to cuda
Now the copy of tensor: 
tensor([[[0.1927, 0.3063, 0.9787, 0.3018],
         [0.9392, 0.1988, 0.9323, 0.9364]],

        [[0.4156, 0.4402, 0.8556, 0.5049],
         [0.8025, 0.3786, 0.3374, 0.0859]],

        [[0.1037, 0.7717, 0.8710, 0.2377],
         [0.3070, 0.6049, 0.1190, 0.8856]]], device='cuda:0')
 is stored on cuda


In [50]:
# 2. index & slice of tensor
tensor = torch.rand((3,4))

print(f"whole tensor: \n {tensor} \n")
print(f"second row: {tensor[1]}")
print(f"third column: {tensor[:,2]}")
print(f"first row fourth column: {tensor[0,3]}")
print(f"1st, 2nd row 1st column: {tensor[0:2,0]}")
print(f"(1,2) and (2,3): {tensor[[0,1],[1,2]]}")

whole tensor: 
 tensor([[0.3399, 0.1456, 0.1010, 0.0518],
        [0.9929, 0.1190, 0.4411, 0.8385],
        [0.6301, 0.3336, 0.7226, 0.5065]]) 

second row: tensor([0.9929, 0.1190, 0.4411, 0.8385])
third column: tensor([0.1010, 0.4411, 0.7226])
first row fourth column: 0.05182623863220215
1st, 2nd row 1st column: tensor([0.3399, 0.9929])
(1,2) and (2,3): tensor([0.1456, 0.4411])


In [65]:
# 3. modify values in tensor
tensor = torch.rand((2,2,3))

print(f"original tensor: \n {tensor} \n")
tensor[0,1,2] = 3
print(f"1st modified tensor: \n {tensor} \n")
tensor[:,1,:] = torch.tensor([-114,-514,1.919810])
print(f"2nd modified tensor: \n {tensor} \n")
tensor[:,1,1] = 999
print(f"3rd modified tensor: \n {tensor} \n")

original tensor: 
 tensor([[[0.5160, 0.9583, 0.4444],
         [0.8749, 0.9285, 0.9861]],

        [[0.7099, 0.5229, 0.0729],
         [0.0023, 0.2074, 0.3989]]]) 

1st modified tensor: 
 tensor([[[5.1597e-01, 9.5831e-01, 4.4440e-01],
         [8.7488e-01, 9.2846e-01, 3.0000e+00]],

        [[7.0990e-01, 5.2286e-01, 7.2904e-02],
         [2.3420e-03, 2.0745e-01, 3.9895e-01]]]) 

2nd modified tensor: 
 tensor([[[ 5.1597e-01,  9.5831e-01,  4.4440e-01],
         [-1.1400e+02, -5.1400e+02,  1.9198e+00]],

        [[ 7.0990e-01,  5.2286e-01,  7.2904e-02],
         [-1.1400e+02, -5.1400e+02,  1.9198e+00]]]) 

3rd modified tensor: 
 tensor([[[ 5.1597e-01,  9.5831e-01,  4.4440e-01],
         [-1.1400e+02,  9.9900e+02,  1.9198e+00]],

        [[ 7.0990e-01,  5.2286e-01,  7.2904e-02],
         [-1.1400e+02,  9.9900e+02,  1.9198e+00]]]) 



In [79]:
# 4. join tensors together
tensor = torch.ones((2,3),dtype=torch.int64)
tensor[:,0] = 0
tensor[:,2] = 2
print(f"Original tensor: \n {tensor} \n")

t1 = torch.cat((tensor,tensor,tensor),dim=0)
print(f"Combined by torch.cat(): \n {t1} \n shape: {t1.shape}") # just combining
t2 = torch.stack((tensor,tensor,tensor),dim=0) # dim等于几，就在哪个维度上复制这个维度的tensor三次
print(f"Combined by torch.stack() \n {t2} \n shape: {t2.shape}") # create a new dimension

Original tensor: 
 tensor([[0, 1, 2],
        [0, 1, 2]]) 

Combined by torch.cat(): 
 tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]) 
 shape: torch.Size([6, 3])
Combined by torch.stack() 
 tensor([[[0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2]]]) 
 shape: torch.Size([3, 2, 3])


In [15]:
# 5. arithmetic operations

t1 = torch.rand((3,))
t2 = torch.rand((3,2))
print(f"{t1.shape} @ {t1.shape}: {(t1 @ t1).shape}")
print(f"{t1.shape} @ {t2.shape}: {(t1 @ t2).shape}") # automatically add a dimention, then removed after calculation
print(f"{t1[None,:].shape} @ {t2.shape}: {(t1.reshape((1,-1)) @ t2).shape}")

# treat last 2 dimensions as matrix, other dimentions apply broadcast(equal shape or one dimention is 1 or one dimension doesn't exist)
t3 = torch.rand((2,1,3,4))
t4 = torch.rand((3,4,3))
print(f"{t3.shape} @ {t4.shape}: {(t3 @ t4).shape}")

torch.Size([3]) @ torch.Size([3]): torch.Size([])
torch.Size([3]) @ torch.Size([3, 2]): torch.Size([2])
torch.Size([1, 3]) @ torch.Size([3, 2]): torch.Size([1, 2])
torch.Size([2, 1, 3, 4]) @ torch.Size([3, 4, 3]): torch.Size([2, 3, 3, 3])


In [17]:
## 快速回收空间建立张量，数值取决于内存里剩下什么
print(torch.empty((1,2,3)))

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])


In [18]:
# element-wise prodect
t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.rand((2,3))
print(f"element wise product: \n{t1 * t2}\n")

element wise product: 
tensor([[0.3620, 0.5090, 1.3216],
        [0.6434, 1.2682, 3.8848]])



In [35]:
# different address
tensor = torch.tensor([[1,2,3],[1,4,1],[2,6,4]])
y1 = tensor * tensor.T
y2 = tensor @ tensor.T
print(y1,id(y1))
print(y2,id(y2))

# same address
res = torch.empty((3,3), dtype=torch.int64)
torch.mul(tensor, tensor.T, out=res)
print(res,id(res))
torch.matmul(tensor, tensor.T, out=res)
print(res,id(res))

tensor([[ 1,  2,  6],
        [ 2, 16,  6],
        [ 6,  6, 16]]) 2413879950736
tensor([[14, 12, 26],
        [12, 18, 30],
        [26, 30, 56]]) 2413880035120
tensor([[ 1,  2,  6],
        [ 2, 16,  6],
        [ 6,  6, 16]]) 2413879949376
tensor([[14, 12, 26],
        [12, 18, 30],
        [26, 30, 56]]) 2413879949376


In [25]:
# 6. turn single value tensor into python numerical value
tensor = torch.ones((2,3),dtype=torch.int64)
y1 = tensor.sum()
print(y1,type(y1))

# use item()
y1 = y1.item()
print(y1,type(y1))

tensor(6) <class 'torch.Tensor'>
6 <class 'int'>


In [34]:
# 7. inplace operation
print(f"original tensor: \n{tensor}\naddress: {id(tensor)}\n ")
# out-of_place: open a new address
y1 = tensor.add(5)
print(f"out-of-place operation: \n{y1}\naddress: {id(y1)}\n ")
# in-place: without chanding address
tensor.add_(5)
print(f"in-place operation: \n{tensor}\naddress: {id(tensor)}\n ")

original tensor: 
tensor([3, 4, 5, 6, 7])
address: 2413880033600
 
out-of-place operation: 
tensor([ 8,  9, 10, 11, 12])
address: 2413879949376
 
in-place operation: 
tensor([ 8,  9, 10, 11, 12])
address: 2413880033600
 


In [37]:
# 8. change to numpy: share same memory
tensor = torch.tensor([1,2,3,4,5])
print(tensor,type(tensor))
n1 = tensor.numpy()
print(n1, type(n1))

# both will change, no matter change which
tensor.add_(1)
print(tensor)
print(n1)
n1 += 1
print(tensor)
print(n1)


tensor([1, 2, 3, 4, 5]) <class 'torch.Tensor'>
[1 2 3 4 5] <class 'numpy.ndarray'>
tensor([2, 3, 4, 5, 6])
[2 3 4 5 6]
tensor([3, 4, 5, 6, 7])
[3 4 5 6 7]


In [33]:
print(tensor.device)

cpu


In [44]:
tensor = torch.tensor([[1,2,3],[4,-5,6],[7,8,9]])
n = tensor.numpy()
print(n.mean())

3.888888888888889
